2018-10-14 16:50:33,085, log_level=INFO,  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2018-10-14 16:50:36,104, log_level=ERROR, Exception possibly due to cache backend.
Traceback (most recent call last):
  File "//anaconda/lib/python2.7/site-packages/flask_cache/__init__.py", line 300, in decorated_function
    timeout=decorated_function.cache_timeout)
  File "//anaconda/lib/python2.7/site-packages/werkzeug/contrib/cache.py", line 317, in set
    pickle.HIGHEST_PROTOCOL))
TypeError: can't pickle generator objects
2018-10-14 16:50:37,125, log_level=ERROR, Exception possibly due to cache backend.
Traceback (most recent call last):
  File "//anaconda/lib/python2.7/site-packages/flask_cache/__init__.py", line 300, in decorated_function
    timeout=decorated_function.cache_timeout)
  File "//anaconda/lib/python2.7/site-packages/werkzeug/contrib/cache.py", line 317, in set
    pickle.HIGHEST_PROTOCOL))
TypeError: can't pickle generator objects
2018-10-14 16:50:37,726, log_level=INFO, 127.0.0.1 - - [14/Oct/2018 16:50:37] "GET /chapters HTTP/1.1" 200 -
2018-10-14 16:50:37,841, log_level=INFO, 127.0.0.1 - - [14/Oct/2018 16:50:37] "GET /static/css/bootstrap.min.css HTTP/1.1" 304 -
2018-10-14 16:50:37,850, log_level=INFO, 127.0.0.1 - - [14/Oct/2018 16:50:37] "GET /static/css/style.css HTTP/1.1" 304 -
2018-10-14 16:50:37,853, log_level=INFO, 127.0.0.1 - - [14/Oct/2018 16:50:37] "GET /static/font-awesome/css/font-awesome.min.css HTTP/1.1" 304 -
2018-10-14 16:50:38,135, log_level=INFO, 127.0.0.1 - - [14/Oct/2018 16:50:38] "GET /static/js/jquery.js HTTP/1.1" 304 -
2018-10-14 16:50:38,150, log_level=INFO, 127.0.0.1 - - [14/Oct/2018 16:50:38] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 -
2018-10-14 16:50:38,175, log_level=INFO, 127.0.0.1 - - [14/Oct/2018 16:50:38] "GET /static/js/jquery.easing.min.js HTTP/1.1" 304 -
2018-10-14 16:50:38,183, log_level=INFO, 127.0.0.1 - - [14/Oct/2018 16:50:38] "GET /static/img/logos/logo3.png HTTP/1.1" 200 -
2018-10-14 16:50:38,240, log_level=INFO, 127.0.0.1 - - [14/Oct/2018 16:50:38] "GET /static/img/banner/banner_home.png HTTP/1.1" 200 -
2018-10-14 16:50:40,296, log_level=INFO, 127.0.0.1 - - [14/Oct/2018 16:50:40] "GET /static/img/faviconit/favicon-32x32.png HTTP/1.1" 200 -
2018-10-14 16:50:40,308, log_level=INFO, 127.0.0.1 - - [14/Oct/2018 16:50:40] "GET /static/img/faviconit/favicon-16x16.png HTTP/1.1" 200 -
2018-10-14 16:50:40,321, log_level=INFO, 127.0.0.1 - - [14/Oct/2018 16:50:40] "GET /static/img/faviconit/favicon-96x96.png HTTP/1.1" 200 -
2018-10-14 16:50:55,972, log_level=ERROR, Exception possibly due to cache backend.
Traceback (most recent call last):
  File "//anaconda/lib/python2.7/site-packages/flask_cache/__init__.py", line 300, in decorated_function
    timeout=decorated_function.cache_timeout)
  File "//anaconda/lib/python2.7/site-packages/werkzeug/contrib/cache.py", line 317, in set
    pickle.HIGHEST_PROTOCOL))
TypeError: can't pickle generator objects
2018-10-14 16:50:56,597, log_level=ERROR, Exception possibly due to cache backend.
Traceback (most recent call last):
  File "//anaconda/lib/python2.7/site-packages/flask_cache/__init__.py", line 300, in decorated_function
    timeout=decorated_function.cache_timeout)
  File "//anaconda/lib/python2.7/site-packages/werkzeug/contrib/cache.py", line 317, in set
    pickle.HIGHEST_PROTOCOL))
TypeError: can't pickle generator objects
2018-10-14 16:50:56,989, log_level=INFO, 127.0.0.1 - - [14/Oct/2018 16:50:56] "GET /chapters HTTP/1.1" 200 -
2018-10-14 16:50:58,965, log_level=INFO, 127.0.0.1 - - [14/Oct/2018 16:50:58] "GET /static/img/faviconit/favicon-32x32.png HTTP/1.1" 200 -
2018-10-14 16:52:27,378, log_level=INFO,  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2018-10-14 16:52:29,434, log_level=ERROR, Exception possibly due to cache backend.
Traceback (most recent call last):
  File "//anaconda/lib/python2.7/site-packages/flask_cache/__init__.py", line 300, in decorated_function
    timeout=decorated_function.cache_timeout)
  File "//anaconda/lib/python2.7/site-packages/werkzeug/contrib/cache.py", line 317, in set
    pickle.HIGHEST_PROTOCOL))
TypeError: can't pickle generator objects
2018-10-14 16:52:30,080, log_level=ERROR, Exception possibly due to cache backend.
Traceback (most recent call last):
  File "//anaconda/lib/python2.7/site-packages/flask_cache/__init__.py", line 300, in decorated_function
    timeout=decorated_function.cache_timeout)
  File "//anaconda/lib/python2.7/site-packages/werkzeug/contrib/cache.py", line 317, in set
    pickle.HIGHEST_PROTOCOL))
TypeError: can't pickle generator objects
2018-10-14 16:52:30,525, log_level=INFO, 127.0.0.1 - - [14/Oct/2018 16:52:30] "GET /chapters HTTP/1.1" 200 -
2018-10-14 16:52:32,329, log_level=INFO, 127.0.0.1 - - [14/Oct/2018 16:52:32] "GET /static/img/faviconit/favicon-32x32.png HTTP/1.1" 200 -
2018-10-14 16:53:11,526, log_level=INFO,  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2018-10-14 16:53:13,900, log_level=ERROR, Exception possibly due to cache backend.
Traceback (most recent call last):
  File "//anaconda/lib/python2.7/site-packages/flask_cache/__init__.py", line 300, in decorated_function
    timeout=decorated_function.cache_timeout)
  File "//anaconda/lib/python2.7/site-packages/werkzeug/contrib/cache.py", line 317, in set
    pickle.HIGHEST_PROTOCOL))
TypeError: can't pickle generator objects
2018-10-14 16:53:14,776, log_level=ERROR, Exception possibly due to cache backend.
Traceback (most recent call last):
  File "//anaconda/lib/python2.7/site-packages/flask_cache/__init__.py", line 300, in decorated_function
    timeout=decorated_function.cache_timeout)
  File "//anaconda/lib/python2.7/site-packages/werkzeug/contrib/cache.py", line 317, in set
    pickle.HIGHEST_PROTOCOL))
TypeError: can't pickle generator objects
2018-10-14 16:53:15,261, log_level=INFO, 127.0.0.1 - - [14/Oct/2018 16:53:15] "GET /chapters HTTP/1.1" 200 -
2018-10-14 16:53:17,227, log_level=INFO, 127.0.0.1 - - [14/Oct/2018 16:53:17] "GET /static/img/faviconit/favicon-32x32.png HTTP/1.1" 200 -
2018-10-14 16:54:57,171, log_level=INFO,  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2018-10-14 16:55:00,567, log_level=ERROR, Exception possibly due to cache backend.
Traceback (most recent call last):
  File "//anaconda/lib/python2.7/site-packages/flask_cache/__init__.py", line 300, in decorated_function
    timeout=decorated_function.cache_timeout)
  File "//anaconda/lib/python2.7/site-packages/werkzeug/contrib/cache.py", line 317, in set
    pickle.HIGHEST_PROTOCOL))
TypeError: can't pickle generator objects
2018-10-14 16:55:01,217, log_level=ERROR, Exception possibly due to cache backend.
Traceback (most recent call last):
  File "//anaconda/lib/python2.7/site-packages/flask_cache/__init__.py", line 300, in decorated_function
    timeout=decorated_function.cache_timeout)
  File "//anaconda/lib/python2.7/site-packages/werkzeug/contrib/cache.py", line 317, in set
    pickle.HIGHEST_PROTOCOL))
TypeError: can't pickle generator objects
2018-10-14 16:55:01,652, log_level=INFO, 127.0.0.1 - - [14/Oct/2018 16:55:01] "GET /chapters HTTP/1.1" 200 -
2018-10-14 16:55:03,639, log_level=INFO, 127.0.0.1 - - [14/Oct/2018 16:55:03] "GET /static/img/faviconit/favicon-32x32.png HTTP/1.1" 200 -
